<?php

/**
 * @author  Mohamed Anis TAKTAK <tak2.anis@gmail.com>
 */

/**
 * Add a textfield class to Block form
 *  Implements hook_form_FORM_ID_alter().
 */
function block_class_form_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if(\Drupal::currentUser()->hasPermission('administer block classes')){
  		$block_id = $form['id']['#default_value'];

  		//Global block id.
	  	$block = \Drupal::entityManager()->getStorage('block')->load($block_id);
	  		
	  	if ( $block ) {
			$plugin_id = $block->getPluginId();
			//Get All configurations.
			$config_factory = \Drupal::configFactory();
			$config = $config_factory->getEditable('block_class.settings')->get($plugin_id);
			$form['add_classes'] = array(
				'#type' => 'textfield',
				'#title' => t('CSS class(es)'),
				'#weight' => 0,
				'#default_value' => $config,
				'#attributes' => array(
					'placeholder' => t('If you don\'t want to add a class, leave it blank.')
				),
				'#description' => t('Customize the styling of this block by adding CSS classes. Separate multiple classes by spaces.')
			);
			
			//Add callback function to save configurations when submit.
			$form['actions']['submit']['#submit'][] = 'add_class_callback';
		}
	}
}

/**
 * Callback to Form block  - Adding classes.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function add_class_callback(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  //Get all configurations.
  $config_factory = \Drupal::configFactory();
  //Get the configurations of blocks classes.
  $block_class = $form_state->getValue('add_classes');
  //Get the current block id.
  $block_id = $form_state->getValue('id');
  $plugin_id = \Drupal::entityManager()->getStorage('block')->load($block_id)->getPluginId();
  //If the block doesn't has a custom class, we don't add this is the configurations.
  if ($plugin_id != '') {
    $config_factory->getEditable('block_class.settings')
      ->set($plugin_id, $block_class)
      ->save(TRUE);
  }
}
/**
 *  Implements hook_preprocess_block().
 */
function block_class_preprocess_block(&$variables) {
  //Get all configurations.
  $config_factory = \Drupal::configFactory();
  $plugins_id = $variables['elements']['#configuration']['id'];
  $block_class = $config_factory->getEditable('block_class.settings')
    ->get($plugins_id);

  if ($variables['configuration']['id'] == $plugins_id) {
    if (isset($variables['attributes']['class'])) {
      $variables['attributes']['class'][1] = $block_class;
    }
    else {
      $variables['attributes']['class'] = array($block_class);
    }
  }
}
